[package]
name = "crypt_guard_sign"
version = "0.1.1"
edition = "2021"
description = "CryptGuardLib is a comprehensive Rust library designed for strong encryption and decryption, incorporating post-quantum cryptography to safeguard against quantum threats. It's geared towards developers who need to embed advanced cryptographic capabilities in their Rust applications."
license = "MIT"
repository = "https://github.com/mm9942/CryptGuardLibSign"
# author = ["mm29942 <mm29942@pm.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = { version = "0.8.3", optional = true }
colored = "2.1.0"
env = "0.0.0"
hex = "0.4.3"
hmac = "0.12.1"
indicatif = "0.17.7"
pqcrypto-traits = "0.3.5"
rand = "0.8.5"
sha2 = "0.10.8"
tempfile = "3.9.0"
tokio = { version = "1.35.1", features = ["full"] }
chacha20  = { version = "0.9.1", optional = true }
byteorder = "1.5.0"
pqcrypto-dilithium = { version = "0.5.0", optional = true }
pqcrypto-falcon = { version = "0.3.0", optional = true }

[features]
dilithium = ["dep:pqcrypto-dilithium"]
default = ["dep:pqcrypto-falcon"]
